### ISSUE TITLE
python: can't open file

### ISSUE THREAD

**Issue by rizviali110** [teared/VEX#10]
I 've configured my vcc path and trying to do a syntax check, its giving me the following error

python: can't open file 'C:\Users\MY_USER\AppData\Roaming\Sublime Text 3\Packages\VEX Syntax\src\compile_and_run.py': [Errno 2] No such file or directory
[Finished in 0.2s with exit code 2]
[cmd: ['python', '-u', 'C:\\Users\\MY_USER\\AppData\\Roaming\\Sublime Text 3\\Packages/VEX Syntax/src/compile_and_run.py', '']]
[dir: C:\Program Files\Sublime Text 3]
.....

not sure what I am missing

**Comment by teared** [comment]
Hi @rizviali110! You probably run the build system from `VEX Syntax` project.

This add-on is called `VEX`. Make sure you have `VEX` installed and then press `Ctrl`+`Shift`+`B` and choose either of `VEX Build`, `VEX Build — As a Snippet` or `VEX Build — As a Library` build, according to the Readme's  `Syntax Check` part.

![VEX build systems](https://i.imgur.com/xymtDSC.png)

Note that you may have two different `VEX Build` commands if you have both add-ons installed

**Comment by rizviali110** [comment]
Thanks, seems like its working, does it echo if I run print "hello"';
if it does, its not doing it.

**Comment by teared** [comment]
It does not execute the code, only compile it to run syntax check. It will not print, therefore.

If you want to execute your code outside Houdini, you can use [`vexexec`](https://www.sidefx.com/docs/houdini/ref/utils/vexexec) program located at the same folder with `vcc` executable. You will have to wrap the code into a CVEX shader function manually.

Example `hello.vfl`:
```
cvex hello()
{
    printf("Hello World");
}
```
And the `Command Prompt`:

```
C:\Users\user>"C:\Program Files\Side Effects Software\Houdini 18.0.597\bin\vexexec.exe" "C:\Users\user\Desktop\hello.vfl"
Hello World
```
