### ISSUE TITLE
How can I format VEX code?

### ISSUE THREAD

**Issue by MisakaCirno** [teared/VEX#13]
This plugin doesn't seem to have the ability to format code.
I also installed SublimeAStyleFormatter from README, but it also doesn't support formatting VEX code.

**Comment by teared** [comment]
Hello @MisakaCirno!

Yes, this add-on have no such feature.
Formatting is done using the SublimeAStyleFormatter add-on.
Here is how you use it:

1. After you installed `SublimeAStyleFormatter` go to:
   _Preferences → Package Settings → SublimeAStyleFormatter → Settings – User_
   ![Image](https://i.imgur.com/qMF4hO1.png)
   Make sure it contains `user_defined_syntax_mode_mapping` configured for `"vex": "c"`
   This way the formatter will treat .vex files as .c files.
   Here is my current settings:
   ```
   {
       "user_defined_syntax_mode_mapping": {
           "vex": "c",
       },
       "options_default": {
           "style": "allman",
           "indent-preproc-block": true,
           "indent-preproc-define": true,
           "break-blocks": "default",
           "unpad-paren": true,
           "add-brackets": true,
           "keep-one-line-blocks": false
       },
   }
   ```
   Go to _Preferences → Package Settings → SublimeAStyleFormatter → Settings – Default_ to read about other possible settings.
2. When you are inside a VEX file, press `Ctrl+Alt+F` to format your code.
   Alternatively, you can do this fromCommand Palette:
   _Tools → Command Palette..._  or `Ctrl+Shift+P`
   Type "format" and select one of SublimeAStyleFormatter operations.
   ![Image](https://i.imgur.com/PQUdGxC.png)

I hope this helps.

**Comment by MisakaCirno** [comment]
> Hello @MisakaCirno!
> 
> Yes, this add-on have no such feature. Formatting is done using the SublimeAStyleFormatter add-on. Here is how you use it:
> 
> 1. After you installed `SublimeAStyleFormatter` go to:
>    _Preferences → Package Settings → SublimeAStyleFormatter → Settings – User_
>    ![Image](https://camo.githubusercontent.com/c7edcf4592ee0cb11b93ba0fb99e6e43d80ddd21cbfadbe1e8ff8f7024e9c550/68747470733a2f2f692e696d6775722e636f6d2f714d4634684f312e706e67)
>    Make sure it contains `user_defined_syntax_mode_mapping` configured for `"vex": "c"`
>    This way the formatter will treat .vex files as .c files.
>    Here is my current settings:
>    ```
>    {
>        "user_defined_syntax_mode_mapping": {
>            "vex": "c",
>        },
>        "options_default": {
>            "style": "allman",
>            "indent-preproc-block": true,
>            "indent-preproc-define": true,
>            "break-blocks": "default",
>            "unpad-paren": true,
>            "add-brackets": true,
>            "keep-one-line-blocks": false
>        },
>    }
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Go to _Preferences → Package Settings → SublimeAStyleFormatter → Settings – Default_ to read about other possible settings.
> 2. When you are inside a VEX file, press `Ctrl+Alt+F` to format your code.
>    Alternatively, you can do this fromCommand Palette:
>    _Tools → Command Palette..._  or `Ctrl+Shift+P`
>    Type "format" and select one of SublimeAStyleFormatter operations.
>    ![Image](https://camo.githubusercontent.com/4181ab1cd9e0509b2f3c7a96a8cc2a39ca881e4b1bd7f28dd54ca914d05a3167/68747470733a2f2f692e696d6775722e636f6d2f505155644778432e706e67)
> 
> I hope this helps.

Thanks! That is what I want!
