### ISSUE TITLE
Problems on Linux

### ISSUE THREAD

**Issue by hubslave** [teared/VEX#2]
Hello, I installed this great package with Package control but when trying to use it on my Linux machine, I kept getting this error when accessing VEX settings: The settings file "res://Packages/VEX/prefs/VEX.sublime-settings" could not be opened.

So I tried to manually clone this repository to Packages folder, which ran fine and created folder named "vex"

But after trying to open Sublime and then VEX settings again, I still kept getting this error:
The settings file "res://Packages/VEX/prefs/VEX.sublime-settings" could not be opened.

I managed to resolve this issue by renaming the folder "vex" to "VEX" since Linux is case sensitive and after that everything is working fine, I can acces the VEX settings just fine. But I think that all the Linux users would be having this issue and would be only able to install this package only manually, not through Package Control.

Please can you have a look at it at maybe rename the "main" folder to VEX or change settings path from "res://Packages/VEX/prefs/VEX.sublime-settings" to "res://Packages/vex/prefs/VEX.sublime-settings" for the new releases?

Thank you very much and have a nice day :)

**Comment by hubslave** [comment]
(Btw I am personal fan of renaming the "main" folder from "vex" to "VEX", since then it looks much more consistent inside the Sublime Editor :) ) - all other languages are displayed in capital letters, or at least beginning with capital letters.

**Comment by teared** [comment]
Hello @hubslave. Sorry for delayed answer.

There is no Package Control distribution for this add-on. You can download it here: https://github.com/teared/vex/releases

Not sure if it will help, but try to make a clean install first.

1. Assuming [this information](http://sublime-text-unofficial-documentation.readthedocs.io/en/latest/basic_concepts.html#the-data-directory) is correct, cleanup VEX-related stuff from this possible locations:
`~/.config/sublime-text-3/Packages/`
`~/.config/sublime-text-3/Packages/User/`
`~/.config/sublime-text-3/Installed Packages/`

2. Install the file from Releases ([current version direct link](https://github.com/teared/vex/releases/download/v6.1/VEX.sublime-package)) there:
`~/.config/sublime-text-3/Installed Packages/VEX.sublime-package`

Properly installed package will be called uppercase "VEX". There will be submenu containing VEX and HScript syntax choices, like for JavaScript.

**Comment by hubslave** [comment]
@teared Thank you very much. I tested the package and it works without problems :) But regarding package control - besides packages you can add repositories to package control (in this case this git) and package control would manage auto updating so users don't have to download every new release. I just thought that maybe it could be handy. But there is this problem that when you add this git to package control as repository, the folder is called "vex" (in small letters) and settings don't work (at least on unix based systems) because they are looking for "VEX" folder (in capital letters). Just my 2 cents :) but anyway thank you very much for publishing and maintaing these packages, they are really great, also the help popups are excellent, I believe that creating such a great piece of work took a lot of time... Thank you :)

**Comment by teared** [comment]
@hubslave, thank you for the info about the problem. Now it's perfectly clear for me. I also tried it myself and got some extra errors even on Windows.

I overlooked the fact someone will use PaCo for something else than just looking up for goodies in the list. Make sure to delete this repo from PaCo repositories, otherwise it will try to replace latest release version with repo archive. 

The project will be renamed after H17 release. By this time it will work with PaCo and properly handle case-sensitive paths.

Enjoy!

**Comment by hubslave** [comment]
Thank you very much :) Have a nice day :)

**Comment by teared** [comment]
Hey @hubslave.

You can now install the add-on using PaCo channel, or continue to use custom repository. I changed the name to upper-case. Don't miss the fact that I split the add-on on two projects: [VEX], [HScript].

Please, let me know if you experience errors trying to access settings now.

[VEX]: https://github.com/teared/VEX/
[HScript]: https://github.com/teared/HScript/

**Comment by teared** [comment]
If you didn't create user settings file yet, it is fine to get such message:

    Unable to open [...]/Packages/VEX/VEX.sublime-settings

possibly followed by Python traceback (some lines omitted): 

    FileNotFoundError: [Errno 2] No such file or directory: '[...]\\Packages\\VEX\\VEX.sublime-settings'

That's how ST informs the user that preferences file not exist yet, and the traceback normally happens when you have non-existing files opened in ST3 tab. Same happens for default package.
