### ISSUE TITLE
Word wrap in help pop-up

### ISSUE THREAD

**Issue by hubslave** [teared/VEX#3]
Hello teared, it's me again :) I just found a small bug - when using help-pop up, some sentences are "cropped", you can't read them to the end. Only way is to increase pop-up width, but some sentences could be even longer than maximum width users are able to show on screen.

Maybe it would be better if help pop-ups would do word wraps?

I also attach a screenshot of the problem:

![word_wrap](https://user-images.githubusercontent.com/29800872/29789107-449b1196-8c35-11e7-99d0-8461f40ff788.png)

Maybe I can help you with it... Eventhough I have nearly zero experience with programming I suppose that I should look somwhere to commands dir - maybe helpcard.py?

**Comment by hubslave** [comment]
I also tested another commands if it's not just problem of prim_attrib command, but another commands with long sentences have the same problem too (for example geounwrap).

**Comment by teared** [comment]
Thanks for the bug-report @hubslave.

That sucks. I have proper word wrap:
![word-wrap](https://user-images.githubusercontent.com/10775653/29928049-718b4fba-8e81-11e7-9421-4490c77260db.png)

I'll look into this. Hope I'll find the reason.

**Comment by teared** [comment]
The issue probably got fixed in ST3 build 3133: https://github.com/SublimeTextIssues/Core/issues/1687

It is in [dev branch](https://www.sublimetext.com/3dev); you may try to upgrade to that "daily build" or wait until next "production build" got released. Not sure when it will happen, but it can happen pretty soon, according to empirical observation on their [release notifier](https://twitter.com/sublimehq).

**Comment by hubslave** [comment]
Yes it is possible that it is bug of Sublime Text, I'm also on HiDPi display so this is probably the cause, as it was also mentioned in the link you provided. I'll probably wait for the next production build and report back if it's better :) Thank you very much for your help :)

**Comment by hubslave** [comment]
@teared today new sublime-text was released and now all help pop-ups show without any issues, thank you very much for help :)

**Comment by teared** [comment]
@hubslave, good to hear the issue was resolved. Thanks!

**Comment by teared** [comment]
@hubslave, good to hear the issue was resolved. Thanks!
