### ISSUE TITLE
Will have vscode version in the future.

### ISSUE THREAD

**Issue by Leroy-X** [teared/VEX#6]
Hi, I am beginner in vex, this project is great, will have vscode version in the future, or maybe notepad++, you know, the sublime not free, and ui of vscode is nice.

https://github.com/melMass/vscode-vex

I find this version, but some small problem. 

thanks.

**Comment by teared** [comment]
Hi! I use Sublime Text 3, so, I probably won't migrate this add-on to VS Code myself.

**Comment by varomix** [comment]
I use that VEX extension in VSCode and works
