### ISSUE TITLE
Houdini 17 update

### ISSUE THREAD

**Issue by BellaCoola** [teared/VEX#7]
Hello, since Houdini 17 was released yesterday, do you plan to reflect new features in this add-on? :)

Thank you very much and have a nice day :)

**Comment by teared** [comment]
Hi, sorry for delay. I will update it for sure! At first glance, there are only [a few functions added in this release](https://www.sidefx.com/docs/houdini/news/17/vex.html), no add-on core functionality should be affected. If something is not working (presumably VCC), check paths in add-on preferences or in system environment variables. Anyway, I'll revisit the add-on soon myself. Thanks!

**Comment by teared** [comment]
The add-on updated for Houdini 17.0. Feel free to reopen this thread if something looks more broken than before.
