### ISSUE TITLE
Houdini 17.5 update

### ISSUE THREAD

**Issue by BellaCoola** [teared/VEX#8]
Hello dear @teared,

since Houdini 17.5 was released few weeks ago, do you plan to reflect new features in this add-on?

Thank you very much for your time and this great repository, have a nice day :)

**Comment by teared** [comment]
Updated both VEX and [HScript](https://github.com/teared/HScript). I'm not aware about any new syntax or language feature introduced in H17.5, but there are a few interesting functions added. I'll reflect it in the release message and relevant places. Thanks, @BellaCoola!
