### ISSUE TITLE
Does not support autocompletion with variable names?

### ISSUE THREAD

**Issue by monci1850** [teared/VEX#9]
Hi, 
It seems that it cannot trigger the auto-complete with variable names, only has VEX functions. 

How should I fix it in the settings?

Thanks and regards

**Comment by teared** [comment]
Hi @monci1850! Did you mean some Houdini environment variables or default attribute bindings like `@ptnum`?

Function auto-completion implemented via [snippets]. There are also snippets for common keywords. The full list: `if`, `else`, `for`, `foreach`, `while`.

There are no snippets for variables. ST3 should automatically suggest existing variable names (or any word) found in open files, so I typically just rely on that.

![Variable auto-competion example GIF](https://i.imgur.com/459PQeE.gif)

[snippets]: https://github.com/teared/VEX/tree/master/snippets

**Comment by monci1850** [comment]
Hi, @teared 
Thanks for your reply. Yes, I meant the custom variables. I don't know why my sublime does not work like your gif. The auto-completion only works for Houdini Functions.  Do you know how to fix that? 

![sublime_vex_autocompletion](https://user-images.githubusercontent.com/55056703/81439732-ce188480-913c-11ea-9126-6e70e077d499.gif)

![sublime_version](https://user-images.githubusercontent.com/55056703/81439969-47b07280-913d-11ea-922a-5d502d97743a.PNG)

**Comment by teared** [comment]
@monci1850 sorry, I was wrong about _"ST3 should automatically suggest existing variable names (or any word) found in open files"_. I use the [AllAutocomplete](https://packagecontrol.io/packages/All%20Autocomplete) add-on. It fits so seamlessly into ST3 that I completely forgot it was installed!

**Comment by monci1850** [comment]
Thanks a lot. After I installed [All Autocomplete](https://packagecontrol.io/packages/All%20Autocomplete), it fixed. Now it's perfect. 
Cheers. :)

**Comment by teared** [comment]
Glad it helped. Take care!
